### ISSUE TITLE
Problem with encrypting and decrypting password saved in file

### ISSUE THREAD

**Issue by speedy-software-ch** [florianheinemann/password-hash-and-salt#3]
Hi Florian

I have a problem decrypting a password which i saved as string in a text file, so i can compare it to the password provided by the user in the login form. Could you give me an example of how you would do that?

Thanks a lot in advance,

Isai

**Comment by florianheinemann** [comment]
Here you go. Play around with `pwdThatUserProvided` to see that it works:

```javascript
var password = require('password-hash-and-salt');
var fs = require('fs');
var crypto = require('crypto');

var myuser = {
    username: 'admin'
};

// Password of user
var pwd = 'mysecret';

// Creating hash and salt
password(pwd).hash(function(error, hash) {
    if(error)
        throw new Error('Something went wrong!');

    // Store hash (incl. algorithm, iterations, and salt)
    myuser.hash = hash;
    var jsonOfMyuser = JSON.stringify(myuser, null, 4);

    // Print myuser
    console.log("myuser object: " + jsonOfMyuser);

    // Create a file name. In this case we create a MD5 hash of it to make sure it doesn't overlap with another file
    var fileName = crypto.createHash('md5').update(myuser.username).digest('hex');

    // Write the file
    fs.writeFile(fileName, jsonOfMyuser, function(err) {
        if(err) {
            console.log(err);
        } else {
            console.log("JSON saved to " + fileName);

            // Read the file. That could be at a very different place in your script
            // For the sake of the example, we create the filename again
            var userThatWantsToLogin = myuser.username;
            var fileToRead = crypto.createHash('md5').update(userThatWantsToLogin).digest('hex');

            // Read file
            console.log("Read file " + fileToRead);
            fs.readFile(fileToRead, function(err, data) {
                if(err) {
                    console.log(err);
                } else {
                    var jsonContent = JSON.parse(data);
                    console.log("Object read from file: " + fileToRead);

                    // Password that the user has typed in and that we want to check
                    var pwdThatUserProvided = 'mysecret';

                    // Verifying a hash
                    password(pwdThatUserProvided).verifyAgainst(jsonContent.hash, function(error, verified) {
                        if(error)
                            throw new Error('Something went wrong!');
                        if(!verified) {
                            console.log("Don't try! We got you!");
                        } else {
                            console.log("User is authenticated!");
                        }
                    });
                }
            })
        }
    }); 
})
```

**Comment by florianheinemann** [comment]
Small update to the script.

**Comment by speedy-software-ch** [comment]
somehow when i ignore the json part which i don't want to use in my application it doesn't work. could i try to hash the newly inserted password in the login procedure, and then compare both hashes with a normal if statement?

**Comment by florianheinemann** [comment]
Can you show me your code? It's not as easy as just comparing it as you have to take into account the salt. I'm pretty sure it's just a matter of reading maybe a `\n` or something from the file that isn't supposed to be there.

**Comment by florianheinemann** [comment]
Also - make sure to convert the data you get from `readFile` into a string! It's a raw buffer otherwise!

```javascript
var password = require('password-hash-and-salt');
var fs = require('fs');
var crypto = require('crypto');

var myuser = {
    username: 'admin'
};

// Password of user
var pwd = 'mysecret';

// Creating hash and salt
password(pwd).hash(function(error, hash) {
    if(error)
        throw new Error('Something went wrong!');

    // Store hash (incl. algorithm, iterations, and salt)
    myuser.hash = hash;

    // Print myuser
    console.log("myuser hash: " + myuser.hash);

    // Create a file name. In this case we create a MD5 hash of it to make sure it doesn't overlap with another file
    var fileName = crypto.createHash('md5').update(myuser.username).digest('hex');

    // Write the file
    fs.writeFile(fileName, myuser.hash, function(err) {
        if(err) {
            console.log(err);
        } else {
            console.log("Hash saved to " + fileName);

            // Read the file. That could be at a very different place
            // For the sake of the example, we create the filename again
            var userThatWantsToLogin = myuser.username;
            var fileToRead = crypto.createHash('md5').update(userThatWantsToLogin).digest('hex');

            // Read file
            console.log("Read file " + fileToRead);
            fs.readFile(fileToRead, function(err, data) {
                if(err) {
                    console.log(err);
                } else {
                    console.log("Data read from file: " + data);

                    // Password that the user has typed in and that we want to check
                    var pwdThatUserProvided = 'mysecret';

                    // Verifying a hash
                    password(pwdThatUserProvided).verifyAgainst(data.toString(), function(error, verified) {
                        if(error)
                            throw new Error('Something went wrong!');
                        if(!verified) {
                            console.log("Don't try! We got you!");
                        } else {
                            console.log("User is authenticated!");
                        }
                    });
                }
            })
        }
    }); 
})
```

**Comment by speedy-software-ch** [comment]
do i need to require "crypto" anyway? even if i don't use the md5 hash for file name?

**Comment by florianheinemann** [comment]
No you wouldn't - But take care that you don't get usernames that are illegal filenames. I'm still not sure why you're actually doing this :D There are so many good, easy-to-use file-based databases...

**Comment by speedy-software-ch** [comment]
you mean like json for example??

**Comment by florianheinemann** [comment]
These could be some options: http://stackoverflow.com/a/11127395/3141929 

Also: If you decide to stick with one file per user. Be 150% sure you clean up the filename with node's built-in functions otherwise it will be easy for hackers to basically overwrite any file on your filesystem by choosing a smart filename

**Comment by speedy-software-ch** [comment]
Here is the Portion of my code that doesn't work, it doesn't show an error, when verifying password against hash, but always gets to "login failed" :+1: 

		case "/admin/login":
		Users_File_Path[9]='0';
		var users_file = String(fs.readFileSync(Users_File_Path));
		users_file=removeNewline(users_file);
		var username;
		var password;
		username = users_file.split('\t');
		password = username[1];
		password_as_string = String(password)
		removeNewline(password_as_string);
		var password_hashed=[];
		password_hashed.hash = password_as_string;
		var url_parts = url.parse(request.url, true);
		var password_correct;
		var password_from_user=String(url_parts.query["password"]);
		response.write(password_from_user);
		var password_hash = String(password_hashed.hash);
		//response.write(password_hash);
			response.write(String(username[0]));
		response.write(url_parts.query["username"]);
		var username_check;
		if(url_parts.query["username"]===String(username[0]))
		{
			var hash_of_password_from_user = password_hasher(password_from_user);
		hash_of_password_from_user.verifyAgainst(String(password_hashed.hash),function (error, verified){
			if(error)
			{
				response.write("error");
			}
				if(verified)
				{
					response.writeHead(200, {"Content-Type": "text/html"});
			response.write("<html><head><meta charset='utf-8'><title>Administrationspanel für die Webseite der V8-Bar</title></head><body bgcolor='#f8fac9'><font face='arial'>");
			response.write("<h1>Administrationspanel</h1>");
			response.write("<a href='content_items'>Beiträge</a>");
			response.write("</font>");
				}
				else
				{
					response.write("<font face='arial'>")
			response.write("Login failed!!!");
			response.write(String(username_check));
			response.write(String(password_correct));
			response.write("</font>");
				}
				});
		}
		else
		{
			username_check=0;
		}
		response.end();
		break;
		case "/admin/create_user":
		response.writeHead(200, {"Content-Type": "text/html"});
		response.write("<html><head><script type='text/javascript'>function check_passwords(){ var password = document.getElementById('password'); var password2= document.getElementById('password2'); if(password.value===password2.value){return true;}else{alert('Kennwörter stimmen nicht überein');return false;}}</script><meta charset='utf-8'><title>Neuen Benutzer erstellen</title></head><body bgcolor='#f8fac9'>");
		//response.write("");
		response.write("<font face='arial'><h1>Neuen Benutzer erstellen</h1>");
		response.write("<form method='get' action='create_user_script' onsubmit='return check_passwords()'>");
		response.write("Benutzername: <input type='text' id='username' name='username'><br>Kennwort: <input type='password' id='password' name='password'><br>Kennwort wiederholen: <input type='password' id='password2'><br><input type='submit' id='erstellen' value='erstellen'>");
		response.write("</form>");
		response.write("</font>");
		response.end();
		break;
		case "/admin/create_user_script":
		response.writeHead(200, {"Content-Type": "text/html"});
		response.write("<html><head><title>Benutzer erstellt</title></head><body bgcolor='#f8fac9'>");
		var url_parts = url.parse(request.url, true);
		var password_to_save=url_parts.query["password"];
		removeNewline(password_to_save);
		var hashed_password= [];
		password_hasher(password_to_save).hash(function(error,h1988ash)
			{
				if(!error)
				{
					hashed_password.hash = hash;
					var username_to_save = url_parts.query["username"];
					var save_data = username_to_save +'\t'+String(hash);
					removeNewline(save_data);
					fs.writeFileSync("users.txt",save_data.toString());
				}
				else
				{
					response.write(error);
				}
			});
		response.end();
		break;
		default:
		response.writeHead(404, { "Content-Type": "text/html"});
		response.write("<html><head><meta charset='utf-8'><title>Die Seite ist nicht verfügbar</title></head><body bgcolor='#f8fac9'>");
		get_header_from_template(response);
		get_menu_from_template(response);
		get_content_from_template(response);
		response.write("<h1>Entschuldigung, diese Seite existiert noch nicht</h1></body></html>");
		response.end();
		break;

**Comment by florianheinemann** [comment]
I noticed that you have `h1988ash` instead of `hash` in one of your lines. Also did you do a `console.log()` of `password_to_save` and `password_from_user` before hashing it? What do they both say? Did you `log()` both hashes and compared them? What does it say?

**Comment by speedy-software-ch** [comment]
thanks for the h1988ash thing, corrected that, and noticed it doesn't even show login failed now.
