### ISSUE TITLE
Invalid hex string

### ISSUE THREAD

**Issue by Stackoverload** [florianheinemann/password-hash-and-salt#5]
Hello! I'm getting the error 'Invalid hex string' when trying to verify the password '1234' and it's salted hash equivalent. The only thing I can think of is that I store the salted hash inside a MySQL server as a varchar. But who knows.

**Comment by florianheinemann** [comment]
Hey, Can you show the string that is saved in the MySQL database? I suspect that there might be no hash stored at all or the readout returns e.g. an error.
Florian

**Comment by Stackoverload** [comment]
pbkdf2$10000$5c4adb2967e4217679da8bd80c13074f465c5a801b2b9db2d94e912b6599bb23a2c44299cecedfb9ecb6f5fe06bdcd676da95852bf63d9a6c97f2d9968c314c4$d32a84915ef99258a8feede44dfa4cc7b741f2e8993aa426716a2195a54d8b2bd73db164283548325967ce87838374b46ef68f83693fee95e
is one of the hashes.

**Comment by florianheinemann** [comment]
Considering that your string is exactly 255 characters long I would assume you've hit the limits of the field you're storing the data in

**Comment by Stackoverload** [comment]
Oh yes. Did not even take that for account. Thanks!

**Comment by florianheinemann** [comment]
Also in answer to another issue: The hashes should be about 270 chars long.
Florian
