### ISSUE TITLE
crypto.pbkdf2 deprecated

### ISSUE THREAD

**Issue by C-Bouthoorn** [florianheinemann/password-hash-and-salt#8]
I suppose this is related to your package, as it's the only one which does something with crypto in my project. When generating a hash with `.hash()`, the following error gets thrown:

`DeprecationWarning: crypto.pbkdf2 without specifying a digest is deprecated. Please specify a digest`

I'm using Node v6.4.0 (npm 3.10.6) with password-hash-and-salt 0.1.3 on Ubuntu 16.04

**Comment by florianheinemann** [comment]
Hi! Fixed with #7 
Cheers
